/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DispatchesRouteImport } from './routes/dispatches'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LogRouteImport } from './routes/log'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as DispatchIdRouteImport } from './routes/dispatch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesRoute = DispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchIdRoute = DispatchIdRouteImport.update({
  id: '/dispatch/$id',
  path: '/dispatch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dispatches': typeof DispatchesRoute
  '/entry': typeof EntryRoute
  '/ledger': typeof LedgerRoute
  '/log': typeof LogRoute
  '/masters': typeof MastersRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/unlock': typeof UnlockRoute
  '/dispatch/$id': typeof DispatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dispatches': typeof DispatchesRoute
  '/entry': typeof EntryRoute
  '/ledger': typeof LedgerRoute
  '/log': typeof LogRoute
  '/masters': typeof MastersRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/unlock': typeof UnlockRoute
  '/dispatch/$id': typeof DispatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dispatches': typeof DispatchesRoute
  '/entry': typeof EntryRoute
  '/ledger': typeof LedgerRoute
  '/log': typeof LogRoute
  '/masters': typeof MastersRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/unlock': typeof UnlockRoute
  '/dispatch/$id': typeof DispatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dispatches'
    | '/entry'
    | '/ledger'
    | '/log'
    | '/masters'
    | '/reports'
    | '/search'
    | '/unlock'
    | '/dispatch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dispatches'
    | '/entry'
    | '/ledger'
    | '/log'
    | '/masters'
    | '/reports'
    | '/search'
    | '/unlock'
    | '/dispatch/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dispatches'
    | '/entry'
    | '/ledger'
    | '/log'
    | '/masters'
    | '/reports'
    | '/search'
    | '/unlock'
    | '/dispatch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DispatchesRoute: typeof DispatchesRoute
  EntryRoute: typeof EntryRoute
  LedgerRoute: typeof LedgerRoute
  LogRoute: typeof LogRoute
  MastersRoute: typeof MastersRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  UnlockRoute: typeof UnlockRoute
  DispatchIdRoute: typeof DispatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches': {
      id: '/dispatches'
      path: '/dispatches'
      fullPath: '/dispatches'
      preLoaderRoute: typeof DispatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/$id': {
      id: '/dispatch/$id'
      path: '/dispatch/$id'
      fullPath: '/dispatch/$id'
      preLoaderRoute: typeof DispatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DispatchesRoute: DispatchesRoute,
  EntryRoute: EntryRoute,
  LedgerRoute: LedgerRoute,
  LogRoute: LogRoute,
  MastersRoute: MastersRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  UnlockRoute: UnlockRoute,
  DispatchIdRoute: DispatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
